# Generated by Django 5.0 on 2023-12-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('student', models.CharField(max_length=300)),
                ('roll_no', models.CharField(max_length=300)),
                ('Class', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
    ]
