# Generated by Django 5.0 on 2023-12-06 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_studentregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.CharField(max_length=100)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.article')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.studentregister')),
            ],
        ),
    ]
