# Generated by Django 5.0 on 2023-12-06 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_studentarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.article')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.studentregister')),
            ],
        ),
    ]
